name: signfiles

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    name: Sign files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/kevfoste/certsign/signdemo
          tags: type=sha, format=long
      
      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
            platforms: linux/amd64,linux/arm/v7,linux/arm64
            push: true
            tags: ${{ steps.docker_meta.outputs.tags }} 
      
      - name: Write signing key
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          
      - name: Sign artifact with cosign
        run: |
          echo 'tags and digest "${TAGS}@${DIGEST}"'
          cosign sign --yes --key cosign.key "${TAGS}@${DIGEST}"
          env:
            TAGS: ${{ steps.docker_meta.outputs.tags }}
            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
            DIGEST: ${{ steps.build-and-push.outputs.digest }}
            

         
          
    
