name: signblobs

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    name: Sign files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up env cosign
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_REPOSITORY: ${{ github.repository }}
          
      
        run: 
          cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY ${{ github.workspace }}/builds/myfile.dll 

      - name: Upload signed blob to GitHub Container Registry
        run:
          cosign upload blob -f ${{ github.workspace }}/builds/myfile.dll ghcr.io/${{ github.repository }}/myfile.dll

      - name: Verify signature
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
        run:
          cosign verify --key env://COSIGN_PUBLIC_KEY  ghcr.io/${{ github.repository }}/myfile.dll
      